/**
 * Abstract Base Class for AI Coding Agents.
 * Standardizes format, directives, and metadata so new agents
 * can be integrated with minimal effort.
 */
export class BaseAgent {
  constructor({ id, name, description, supportedModes = ['build', 'fix'] }) {
    if (!id || !name) {
      throw new Error('Agent must specify id and name');
    }
    this.id = id;
    this.name = name;
    this.description = description || '';
    this.supportedModes = supportedModes;
  }

  /**
   * Returns agent-specific directives or rules.
   * Can be overridden by subclasses.
   */
  getDirectives(mode, config = {}) {
    return [];
  }

  /**
   * Returns guidance for how prompts and commands should be optimized
   * for this agent so Gemini can reason and tailor the refined command.
   * @returns {string}
   */
  getOptimizationGuidelines() {
    return 'Provide a clear, deterministic, and self-contained command with unambiguous acceptance criteria.';
  }

  /**
   * Formats the final compiled prompt for this specific agent's ingestion syntax.
   * If a high-quality refinedCommand is generated by Gemini, it uses or wraps it appropriately.
   */
  formatPrompt({
    mode,
    primaryIntent,
    rawPrompt,
    refinedCommand,
    projectRules = [],
    structuredPlan = [],
    config = {},
  }) {
    if (refinedCommand && typeof refinedCommand === 'string' && refinedCommand.trim().length > 0) {
      return refinedCommand.trim();
    }
    throw new Error(`formatPrompt() must be implemented by ${this.constructor.name}`);
  }
}

export default BaseAgent;
